# Generated by Django 4.0.5 on 2022-11-13 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_annual_sales', models.BigIntegerField(default='0')),
                ('user_no_of_staff', models.IntegerField(blank=True, null=True)),
                ('user_industry', models.CharField(blank=True, max_length=50, null=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_student_details',
                'managed': True,
            },
        ),
    ]
