# Generated by Django 4.0.5 on 2022-11-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_studentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='user_annual_sales',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='user_industry',
        ),
    ]
