# Generated by Django 4.0.5 on 2022-11-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_remove_studentdetails_user_annual_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
