# Generated by Django 4.0.5 on 2022-11-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_customuser_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contacts_update_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country_name_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='device_details',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='device_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='invite_friends',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mysql_best_friend_user_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mysql_lover_user_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_verified_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='remember_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='no_of_update',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
