# Generated by Django 4.0.5 on 2022-11-14 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0005_remove_customuser_contacts_update_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='user_no_of_staff',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='updated_at_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
