# Generated by Django 4.0.5 on 2022-11-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0006_remove_studentdetails_user_no_of_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
