# Generated by Django 4.0.5 on 2022-11-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0007_studentdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
